[versions]
jspecify = "1.0.0"
netty = "4.2.12.Final"
slf4j = "2.0.17"
jackson = "3.1.3"
junit = "6.0.3"
junit5-base = "5.0.0"
junit-platform = "6.0.3"
hamcrest = "3.0"
mockito = "5.23.0"
httpclient = "5.3.1"
jsonpath = "3.0.0"
freemarker = "2.3.34"
jsonassert = "1.5.3"
tinylog = "2.7.0"
commons-cli = "1.11.0"
proguard = "7.9.1"
websocket = "2.0.0"
tyrus-client = "2.0.0"
maven-publish-plugin = "0.36.0"

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
netty-codec-http = { module = "io.netty:netty-codec-http", version.ref = "netty" }
netty-codec-http2 = { module = "io.netty:netty-codec-http2", version.ref = "netty" }
netty-handler = { module = "io.netty:netty-handler", version.ref = "netty" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-xml = { module = "tools.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
json-path = { module = "com.jayway.jsonpath:json-path", version.ref = "jsonpath" }
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commons-cli" }
tinylog-slf4j = { module = "org.tinylog:slf4j-tinylog", version.ref = "tinylog" }
tinylog-impl = { module = "org.tinylog:tinylog-impl", version.ref = "tinylog" }

hamcrest-core = { module = "org.hamcrest:hamcrest-core", version.ref = "hamcrest" }
hamcrest-library = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
httpclient-fluent = { module = "org.apache.httpcomponents.client5:httpclient5-fluent", version.ref = "httpclient" }
jsonassert = { module = "org.skyscreamer:jsonassert", version.ref = "jsonassert" }
websocket-api = { module = "jakarta.websocket:jakarta.websocket-api", version.ref = "websocket" }
tyrus-client = { module = "org.glassfish.tyrus.bundles:tyrus-standalone-client", version.ref = "tyrus-client" }
junit4 = { module = "junit:junit", version = "4.7" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-jupiter5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5-base" }
junit-jupiter5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5-base" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

[plugins]
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish-plugin" }
