plugins {
    id 'moco-java-conventions'
}

apply from: rootProject.file('moco-publishing.gradle')

evaluationDependsOn(':moco-core')
evaluationDependsOn(':moco-runner')

def coreTestOutput = project(':moco-core').sourceSets.test.output
def runnerTestOutput = project(':moco-runner').sourceSets.test.output

dependencies {
    api(project(':moco-core'))
    api(project(':moco-runner'))
    api(libs.junit4)

    testImplementation(coreTestOutput)
    testImplementation(runnerTestOutput)

    testImplementation(libs.hamcrest.core)
    testImplementation(libs.hamcrest.library)
    testImplementation(libs.httpclient.fluent)
}
